

language: php

php:
    - 5.5
    - 5.6
    - 7.0

services:
    - postgresql

before_script:
    - createdb -Upostgres -EUTF-8 -Ttemplate0 zapstore_test_db
    - composer install -no --prefer-dist

script:
    - php ./vendor/bin/phpunit -c phpunit.xml

after_success:
    - curl -s https://codecov.io/bash | bash

